name: loader_search_bar
description: Flutter widget integrating search field feature into app bar.
version: 1.0.2
author: Tomasz Wyrowinski <tomwyr@hotmail.com>
homepage: https://github.com/tomwyr/loader-search-bar

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
